python3-flit_core
python3-installer
python3-wheel
python3-pyproject-hooks
python3-build
python3-packaging-opt
python3-setuptools-opt
python-zipp
python-importlib_metadata
sphinxcontrib-serializinghtml
sphinxcontrib-qthelp
sphinxcontrib-jsmath
sphinxcontrib-htmlhelp
sphinxcontrib-devhelp
sphinxcontrib-applehelp
snowballstemmer
python3-pytz
python3-babel
imagesize
alabaster
Sphinx
DevIL
AviSynthPlus
